server:
  port: 9000

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: TRACE
        security.oauth2: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teamup
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
