server:
  port: 8090

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: TRACE
        security.oauth2: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
